### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by spdegabrielle** [Metaxal/rascas#1]
I think 4b in the Apache licence terms for dharmatech/mpl require a change log on each file modified;

https://github.com/dharmatech/mpl/blob/master/LICENSE

**Comment by Metaxal** [comment]
Thanks for pointing it out!
Annoyingly, I'll have to do that on all files...

**Comment by spdegabrielle** [comment]
>   (b) You must cause any modified files to carry prominent notices stating that You changed the files; 

PS This is great - thanks for porting this.
PPS have you seen https://github.com/soegaard/racket-cas

**Comment by Metaxal** [comment]
I believe this is now fixed. Feel free to reopen the issue if you think something else/more should be done.

I had forgotten about racket-cas in fact :-/ I might have started there instead.
